In [31]:
#building an Artificial Neural Network

#import libraries and modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

from sklearn import preprocessing

In [32]:
#import dataset
ds = pd.read_csv("Churn_Modelling.csv")

In [33]:
#label encode 'gender' feature
lb_encode = preprocessing.LabelEncoder()
ds['Gender'] = lb_encode.fit_transform(ds['Gender'])

#one hot encode 'Geography' feature
ds = pd.get_dummies(ds, columns = ['Geography'])

print(ds.head(3))

   RowNumber  CustomerId   Surname  CreditScore  Gender  Age  Tenure  \
0          1    15634602  Hargrave          619       0   42       2   
1          2    15647311      Hill          608       0   41       1   
2          3    15619304      Onio          502       0   42       8   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       0.00              1          1               1        101348.88   
1   83807.86              1          0               1        112542.58   
2  159660.80              3          1               0        113931.57   

   Exited  Geography_France  Geography_Germany  Geography_Spain  
0       1                 1                  0                0  
1       0                 0                  0                1  
2       1                 1                  0                0  


In [34]:
#create dependant and independant variables
x = ds.iloc[:,3:-1].values
y = ds.iloc[:,-1].values

print(x)
print(y)

[[619.   0.  42. ...   1.   1.   0.]
 [608.   0.  41. ...   0.   0.   0.]
 [502.   0.  42. ...   1.   1.   0.]
 ...
 [709.   0.  36. ...   1.   1.   0.]
 [772.   1.  42. ...   1.   0.   1.]
 [792.   0.  28. ...   0.   1.   0.]]
[0 1 0 ... 0 0 0]


In [35]:
#split dataset into training set and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)


In [36]:
#feature scaling: compulsory for deep learning.
#feature scaling ALL features

sc = preprocessing.StandardScaler()

#scale both variables seperately, to prevent information leak.
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [37]:
#initialization of ANN
ann = tf.keras.models.Sequential()

#add input layer

#creating 6 neurons
# #setting the activation function as the rectifier linear functions
layerOne = tf.keras.layers.Dense(units=6, activation='relu')

#add first layer to our ANN
ann.add(layerOne)

#second layer
layerTwo = tf.keras.layers.Dense(units=6, activation='relu')

#add second layer to our ANN
ann.add(layerTwo)

#output layer
layerOut = tf.keras.layers.Dense(units=1, activation='sigmoid')

#add output layer to our ANN
ann.add(layerOut)


In [38]:
#training the ANN

#compile ANN
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

#training ANN on training set
ann.fit(x_train, y_train, batch_size= 32, epochs= 100)


Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5306 - accuracy: 0.7379
Epoch 2/100
250/250 [==============================] - 0s 975us/step - loss: 0.3250 - accuracy: 0.8300
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1089 - accuracy: 0.9872
Epoch 4/100
250/250 [==============================] - 0s 968us/step - loss: 0.0302 - accuracy: 0.9999
Epoch 5/100
250/250 [==============================] - 0s 979us/step - loss: 0.0114 - accuracy: 1.0000
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.0053 - accuracy: 1.0000
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.0029 - accuracy: 1.0000
Epoch 8/100
250/250 [==============================] - 0s 913us/step - loss: 0.0017 - accuracy: 1.0000
Epoch 9/100
250/250 [==============================] - 0s 956us/step - loss: 0.0011 - accuracy: 1.0000
Epoch 10/100
250/250 [==============================] - 0s 934us/step - loss: 7.9

In [42]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5

1/1 [==============================] - 0s 16ms/step


array([[False]])